### ISSUE TITLE
Error when upgrading to Kotlin 1.0.0-beta-1103

### ISSUE THREAD

**Issue by lkogler** [damianpetla/kotlin-dagger-example#5]
Hi! I found this project very helpful to see how to set up kotlin with dagger!  But when I tried to use the same method in my app, it didn't work.  I realized that it is because I was using a newer version of Kotlin (version 1.0.0-beta-1103).

If you try updating the Kotlin version in this repo, you will get an error like this:
`java.lang.NoSuchMethodError: No virtual method provideLocationManager$app_compileDebugKotlin()Landroid/location/LocationManager; in class Lorg/loop/example/AndroidModule;`

Unfortunately, I don't know any solution for this problem.  Do you have any ideas?

**Comment by damianpetla** [comment]
@lkogler I have upgraded project to Kotlin Beta and fixed `AndroidModule` class. When I was moving before module from Java to Kotlin, all functions got `internal` modifier which I missed. Removing `internal` fixed the problem

**Comment by lkogler** [comment]
Ah, great, thanks!
